version: 2

jobs:
  build:
    docker:
      - image: nixos/nix
    working_directory: ~/rules_nixpkgs
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            export NIX_PATH=nixpkgs=$PWD/nix/default.nix
            apk update --no-progress && apk --no-progress add bash ca-certificates
            nix-env -iA nixpkgs.bazel nixpkgs.gcc
      - run:
          name: Run tests
          command: bazel test //...
