version: 2

jobs:
  build:
    docker:
      - image: nixos/nix
    working_directory: ~/rules_nixpkgs
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            export NIX_PATH=nixpkgs=https://github.com/nixos/nixpkgs/archive/75942f96b3f7136cdc9cc7d9704824f17fabec02.tar.gz
            apk update --no-progress && apk --no-progress add bash ca-certificates
            nix-env -iA nixpkgs.bazel nixpkgs.gcc
      - run:
          name: Run tests
          command: bazel test //...
