version: 2

jobs:
  build:
    docker:
      - image: nixos/nix:2.3
    working_directory: ~/rules_nixpkgs
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apk update --no-progress && apk --no-progress add bash ca-certificates git
      - run:
          name: Run tests
          command: |
            nix-shell --pure --run 'bazel test --test_output errors //...'
